import type { EditorPreferences } from './schema';

export const DEFAULT_EDITOR_PREFERENCES: EditorPreferences = {
  gridSnap: true,
  slabCutClearance: 0,
  slabEdgeAllowance: 0,
  defaultSlabW: 126,
  defaultSlabH: 63,
  showGrid: true,
  showDims: true,
  showSinkCenterlines: true,
  showManualDims: true,
  showSeams: true,
  showEdgeProfiles: true,
  edgeLabelMode: 'text',
  showEdgeLegend: true,
  showPieceFills: true,
  pieceFillOpacity: 1,
  showSlabMaterial: true,
  showNotes: true,
  showLines: true,
  showLabels: true,
  showCutoutLabels: true,
  showSplashLabels: true,
  showSplashDims: true,
  showSplashLabelDims: true,
  showLabelDims: true,
  showRadiusLabels: true,
  showRoomFeatures: true,
  roomFeatureOpacity: 1,
  showRoomFeatureLabels: true,
  showRoomCabinets: true,
  showRoomFillersPanels: true,
  showRoomAppliances: true,
  showRoomWalls: true,
  dimPrecision: 16,
  dimFormat: 'fraction',
  workspaceViews: null,
};
